"""add_users_organizations_multitenancy

Revision ID: a742fef2a815
Revises: n8o9p0q1r2s3
Create Date: 2026-06-11 11:30:01.758338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a742fef2a815'
down_revision: Union[str, Sequence[str], None] = 'n8o9p0q1r2s3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('oms_id', sa.String(length=256), nullable=True),
    sa.Column('connection_id', sa.String(length=512), nullable=True),
    sa.Column('suz_api_url', sa.String(length=512), nullable=True),
    sa.Column('true_api_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('aggregation_documents', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_aggregation_documents_org_id'), 'aggregation_documents', ['org_id'], unique=False)
    op.create_foreign_key(None, 'aggregation_documents', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('devices', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_devices_org_id'), 'devices', ['org_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('document_upds', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_upds_org_id'), 'document_upds', ['org_id'], unique=False)
    op.create_foreign_key(None, 'document_upds', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('emission_orders', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('uq_emission_orders_suz_order_id'), table_name='emission_orders', postgresql_where='(suz_order_id IS NOT NULL)')
    op.create_index(op.f('ix_emission_orders_org_id'), 'emission_orders', ['org_id'], unique=False)
    op.create_foreign_key(None, 'emission_orders', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('gtin_extra_fields', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_gtin_extra_fields_org_id'), 'gtin_extra_fields', ['org_id'], unique=False)
    op.create_foreign_key(None, 'gtin_extra_fields', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('label_templates', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_label_templates_org_id'), 'label_templates', ['org_id'], unique=False)
    op.create_foreign_key(None, 'label_templates', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('operation_logs', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_operation_type'), table_name='operation_logs')
    op.create_index(op.f('ix_operation_logs_org_id'), 'operation_logs', ['org_id'], unique=False)
    op.create_foreign_key(None, 'operation_logs', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_cards', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_product_cards_org_id'), 'product_cards', ['org_id'], unique=False)
    op.create_foreign_key(None, 'product_cards', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('return_documents', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_return_documents_org_id'), 'return_documents', ['org_id'], unique=False)
    op.create_foreign_key(None, 'return_documents', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('suz_tokens', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_suz_tokens_org_id'), 'suz_tokens', ['org_id'], unique=False)
    op.create_foreign_key(None, 'suz_tokens', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('utilisation_reports', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_utilisation_reports_org_id'), 'utilisation_reports', ['org_id'], unique=False)
    op.create_foreign_key(None, 'utilisation_reports', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('withdrawal_reports', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_withdrawal_reports_org_id'), 'withdrawal_reports', ['org_id'], unique=False)
    op.create_foreign_key(None, 'withdrawal_reports', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawal_reports', type_='foreignkey')
    op.drop_index(op.f('ix_withdrawal_reports_org_id'), table_name='withdrawal_reports')
    op.drop_column('withdrawal_reports', 'org_id')
    op.drop_constraint(None, 'utilisation_reports', type_='foreignkey')
    op.drop_index(op.f('ix_utilisation_reports_org_id'), table_name='utilisation_reports')
    op.drop_column('utilisation_reports', 'org_id')
    op.drop_constraint(None, 'suz_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_suz_tokens_org_id'), table_name='suz_tokens')
    op.drop_column('suz_tokens', 'org_id')
    op.drop_constraint(None, 'return_documents', type_='foreignkey')
    op.drop_index(op.f('ix_return_documents_org_id'), table_name='return_documents')
    op.drop_column('return_documents', 'org_id')
    op.drop_constraint(None, 'product_cards', type_='foreignkey')
    op.drop_index(op.f('ix_product_cards_org_id'), table_name='product_cards')
    op.drop_column('product_cards', 'org_id')
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.drop_index(op.f('ix_operation_logs_org_id'), table_name='operation_logs')
    op.create_index(op.f('ix_operation_logs_operation_type'), 'operation_logs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.drop_column('operation_logs', 'org_id')
    op.drop_constraint(None, 'label_templates', type_='foreignkey')
    op.drop_index(op.f('ix_label_templates_org_id'), table_name='label_templates')
    op.drop_column('label_templates', 'org_id')
    op.drop_constraint(None, 'gtin_extra_fields', type_='foreignkey')
    op.drop_index(op.f('ix_gtin_extra_fields_org_id'), table_name='gtin_extra_fields')
    op.drop_column('gtin_extra_fields', 'org_id')
    op.drop_constraint(None, 'emission_orders', type_='foreignkey')
    op.drop_index(op.f('ix_emission_orders_org_id'), table_name='emission_orders')
    op.create_index(op.f('uq_emission_orders_suz_order_id'), 'emission_orders', ['suz_order_id'], unique=True, postgresql_where='(suz_order_id IS NOT NULL)')
    op.drop_column('emission_orders', 'org_id')
    op.drop_constraint(None, 'document_upds', type_='foreignkey')
    op.drop_index(op.f('ix_document_upds_org_id'), table_name='document_upds')
    op.drop_column('document_upds', 'org_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_org_id'), table_name='devices')
    op.drop_column('devices', 'org_id')
    op.drop_constraint(None, 'aggregation_documents', type_='foreignkey')
    op.drop_index(op.f('ix_aggregation_documents_org_id'), table_name='aggregation_documents')
    op.drop_column('aggregation_documents', 'org_id')
    op.drop_table('organizations')
    op.drop_table('users')
    # ### end Alembic commands ###
